### ISSUE TITLE
[QUESTION]  Out of memory deserializing

### ISSUE THREAD

**Issue by jon-christensen-ag** [ZiggyCreatures/FusionCache#182] opened 2023-11-06 14:49 UTC
We have recently added caching to our api using FusionCache and, in production, we are getting the below exception when we try to retrieve our list of Users.  We are using the FusionCacheNewtonsoftJsonSerializer with default settings:

```
.WithSerializer(
    new FusionCacheNewtonsoftJsonSerializer()
);
```

The data isn't huge (at least I don't think so) at 38,000 rows from the database.  Any thoughts on what we can do to avoid these errors?  Any serializer settings that would help?

We are on v.0.20 of FusionCache and 13.0.3 of Newtonsoft.

```
System.OutOfMemoryException:
   at System.String.CreateStringFromEncoding (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Text.UTF8Encoding.GetString (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Text.Encoding.GetString (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Text.UTF8Encoding+UTF8EncodingSealed.GetString (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at ZiggyCreatures.Caching.Fusion.Serialization.NewtonsoftJson.FusionCacheNewtonsoftJsonSerializer.Deserialize (ZiggyCreatures.FusionCache.Serialization.NewtonsoftJson, Version=0.20.0.0, Culture=neutral, PublicKeyToken=null: /_/src/ZiggyCreatures.FusionCache.Serialization.NewtonsoftJson/FusionCacheNewtonsoftJsonSerializer.cs:35)
   at ZiggyCreatures.Caching.Fusion.Serialization.NewtonsoftJson.FusionCacheNewtonsoftJsonSerializer.DeserializeAsync (ZiggyCreatures.FusionCache.Serialization.NewtonsoftJson, Version=0.20.0.0, Culture=neutral, PublicKeyToken=null: /_/src/ZiggyCreatures.FusionCache.Serialization.NewtonsoftJson/FusionCacheNewtonsoftJsonSerializer.cs:47)
   at ZiggyCreatures.Caching.Fusion.Internals.Distributed.DistributedCacheAccessor+<TryGetEntryAsync>d__16`1.MoveNext (ZiggyCreatures.FusionCache, Version=0.20.0.0, Culture=neutral, PublicKeyToken=null: /_/src/ZiggyCreatures.FusionCache/Internals/Distributed/DistributedCacheAccessor_Async.cs:182)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Threading.Tasks.ValueTask`1.get_Result (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1+ConfiguredValueTaskAwaiter.GetResult (System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at ZiggyCreatures.Caching.Fusion.FusionCache+<GetOrSetEntryInternalAsync>d__45`1.MoveNext (ZiggyCreatures.FusionCache, Version=0.20.0.0, Culture=neutral, PublicKeyToken=null: /_/src/ZiggyCreatures.FusionCache/FusionCache_Async.cs:251)
```

**Comment by jodydonetti** [comment] 2023-11-07 23:38
Hi @jon-christensen-ag and thanks for using FusionCache!

Without more information I can't really know, but since the problem is during deserialization and FusionCache does not provide a serializer but only act as a bridge towards existing ones, and the one you are using seems to be Newtonsoft Json (a.k.a. Json.NET), the problem is most definitely there. Usually in this case it's a circular reference or a wrong configuration with the serializer.

What I would suggest is to try to serialize and deserialize back the same data that you are now caching, using directly Newtonsoft Json, and see what happens: since FusionCache just calls that it's very much probable that you will get the same error.

Hope this helps, let me know if it did work.

**Comment by jodydonetti** [comment] 2023-11-08 13:04
To be clear, this is the code that act as the bridge (a.m.a. adapter) between FusionCache and Newtonsoft Json https://github.com/ZiggyCreatures/FusionCache/blob/main/src/ZiggyCreatures.FusionCache.Serialization.NewtonsoftJson/FusionCacheNewtonsoftJsonSerializer.cs .

As you can see it just forwards the call, that's all.

**Comment by jodydonetti** [comment] 2023-11-11 09:55
Closing this, as no answer.

Will reopen if needed.

**Closed by jodydonetti** 2023-11-11 09:55 UTC
