### ISSUE TITLE
[BUG] FailSafe max duration is somehow ignored 

### ISSUE THREAD

**Issue by sabbadino** [ZiggyCreatures/FusionCache#229] opened 2024-04-10 11:30 UTC
## Describe the bug
given these settings 
"Duration": "00:00:15",
"IsFailSafeEnabled": true,
"FailSafeMaxDuration": "00:01:00", 
"FailSafeThrottleDuration": "00:00:01"

using redis for distriubed cache and backplan 

 ```
builder.Services.AddFusionCache().WithDefaultEntryOptions(fusionCacheSettingConfig.DefaultFusionCacheEntryOptions)
     // ADD JSON.NET BASED SERIALIZATION FOR FUSION CACHE
     .WithSerializer(
         new FusionCacheSystemTextJsonSerializer()
     )
     // ADD REDIS DISTRIBUTED CACHE SUPPORT
     .WithDistributedCache(
         new RedisCache(new RedisCacheOptions {  InstanceName= "fusionCacheApi", Configuration = builder.Configuration["redis:connectionString"] })
     )  // ADD THE FUSION CACHE BACKPLANE FOR REDIS
     .WithBackplane(
         new RedisBackplane(new RedisBackplaneOptions() { Configuration = builder.Configuration["redis:connectionString"] })
     );

```
I see the entry with the correct expiration ( the one of fail safe) in redis ..

as long has the call fail within the FailSafeMaxDuration i see in the logs 
ZiggyCreatures.Caching.Fusion.FusionCache: Warning: FUSION [N=FusionCache I=39f93b2ecaf94426aae009f767fbc7b2] (O=0HN2P9TVTIJ21 K=a): FAIL-SAFE activated **(from distributed)**

When the 1 minute is elapsed , the entry disappear from redis .. but i don't get an error .. message become
ZiggyCreatures.Caching.Fusion.FusionCache: Warning: FUSION [N=FusionCache I=39f93b2ecaf94426aae009f767fbc7b2] (O=0HN2P9TVTIJ32 K=a): FAIL-SAFE activated **(from memory)**

the call start to fail later .. something like 2 minute or so 

## Expected behavior
I expect to get an error after FailSafeMaxDuration has passed 

## Versions
I've encountered this issue on:
- FusionCache version
 <PackageReference Include="ZiggyCreatures.FusionCache" Version="1.0.0" />
 <PackageReference Include="ZiggyCreatures.FusionCache.Backplane.StackExchangeRedis" Version="1.0.0" />
 <PackageReference Include="ZiggyCreatures.FusionCache.Serialization.SystemTextJson" Version="1.0.0" />

- .NET version
8.0
- OS version
-windows 11
- azure cache for Redis

**Comment by jodydonetti** [comment] 2024-04-10 11:32
Hi @sabbadino , may this be a duplicate of [this](https://github.com/ZiggyCreatures/FusionCache/issues/212)?

**Comment by sabbadino** [comment] 2024-04-11 12:16
@jodydonetti ,  looks like for memory cache ExpirationScanFrequency default is 1 minute .. this would explain why i still see around for some minutes the value after the desired expiration .. 

however setting 

 builder.Services.AddMemoryCache(o =>
 {
     o.ExpirationScanFrequency = TimeSpan.FromSeconds(1);
 });
did not make any difference 

note that i am running in release mode

**Comment by sabbadino** [comment] 2024-04-11 13:19
still not sure .. it seems IMeMoryCache check for expiration on get 

```
 internal MemoryCacheEntry Get(MemoryCacheKey key) {
        MemoryCacheEntry entry = _entries[key] as MemoryCacheEntry;
        // has it expired?
        if (entry != null && entry.UtcAbsExp <= DateTime.UtcNow) {
            Remove(key, entry, CacheEntryRemovedReason.Expired);
            entry = null;
        }
        // update outside of lock
        UpdateExpAndUsage(entry);
        return entry;
    }
```

**Comment by jodydonetti** [comment] 2024-04-15 08:06
Update: ok I think I've found the culprit, working on the best way to make the change considering all the edge cases.

**Comment by jodydonetti** [comment] 2024-04-24 08:04
Hi, I just release [v1.1.0](https://github.com/ZiggyCreatures/FusionCache/releases/tag/v1.1.0) 🥳

**Closed by jodydonetti** 2024-04-24 08:04 UTC
